### ISSUE TITLE
Discouraging use of Pkg.BinaryPlatforms

### ISSUE THREAD

**Issue by mkitti** [PeaceFounder/AppBundler.jl#4]
Over in Pkg.jl, I'm trying to fix invalidations. AppBunder is using the old `Pkg.BinaryPlatforms` API rather than sticking with the newer `Base.BinaryPlatforms`.

One of my [proposed fixes](https://github.com/JuliaLang/Pkg.jl/pull/3736) involves making `Pkg.BinaryPlatforms.Linux` and the related platform types into a constructor for `Base.BinaryPlatforms.Platform`. Methods such as `Sys.islinux` should continue to work in the expected way.

```julia
julia> Pkg.BinaryPlatforms.Linux(:x86_64) |> typeof
Base.BinaryPlatforms.Platform

julia> Sys.islinux(Pkg.BinaryPlatforms.Linux(:x86_64))
true
```

Could you consider refactoring to not use `Pkg.BinaryPlatforms.Linux` as a type?

https://github.com/JuliaLang/Pkg.jl/pull/3736

**Comment by JanisErdmanis** [comment]
I am unsure if I would like to go the `Val` route. The function signatures would get longer with additional type information instead of being picked up directly from a platform type. 

An alternative route would be to subtype `AbstractPlatform` in `AppBundler` to create `Linux`, `MacOS`, and `Windows` types. I have to think about this more.

**Comment by mkitti** [comment]
Using `Val` to dispatch in this way is roughly equivalent to appending a `_linux`, `_windows`, and `_macos` version of the function.

The main reason for abandoning the `Linux <: AbstractPlatform` approach is because this leads to excess specialization and thus additional compilation and latency.

`Val` here is used just to dispatch the primary function. 

With `Linux <: AbstractPlatform` you would need a specialized `arch` or `unwrap` and thus get many versions of these functions for each operating system. You could define an `unwrap` with `@nospecialize`, but now you end up doing dynamic dispatch.

The other reason for abandoning `Linux <: AbstractPlatform` is this invalidates a lot of code in the system image leading to recompilation. This problem arises now since Pkg is no longer part of the system image as of Julia 1.11.

**Comment by JanisErdmanis** [comment]
Closing as this change is no longer needed, according to https://github.com/JuliaLang/Pkg.jl/pull/3742

**Comment by mkitti** [comment]
Note that https://github.com/JuliaLang/Pkg.jl/pull/3742 introduces a new problem at least temporarily.

Types in `Pkg.BinaryPlatforms` would no longer be subtypes of `Base.BinaryPlatforms.AbstractPlatform`, at least temporarily.

Subsequent reorganization of `Base.BinaryPlatforms` might be able to restore the relationship.

**Comment by JanisErdmanis** [comment]
That is good to know. That seems, however, a minor convenience as I will simply define in the codebase `const AbstractPlatform = Union{Linux, MacOS, Windows, Platform}` and leave everything else as is.

**Comment by mkitti** [comment]
That PR creates a `Pkg.BinaryPlatforms.AbstractPlatform`. You might want 

```
const AbstractPlatforms = Union{Base.BinaryPlatforms.AbstractPlatform, Pkg.BinaryPlatforms.AbstractPlatform}
```
